import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifAf,
  cifAl,
  cifDz,
  cifAd,
  cifAo,
  cifAg,
  cifAr,
  cifAm,
  cifAu,
  cifAt,
  cifAz,
  cifBs,
  cifBh,
  cifBd,
  cifBb,
  cifBy,
  cifBe,
  cifBz,
  cifBj,
  cifBt,
  cifBo,
  cifBa,
  cifBw,
  cifBr,
  cifBn,
  cifBg,
  cifBf,
  cifBi,
  cifKh,
  cifCm,
  cifCa,
  cifCv,
  cifCf,
  cifTd,
  cifCl,
  cifCn,
  cifCo,
  cifKm,
  cifCr,
  cifHr,
  cifCu,
  cifCy,
  cifCz,
  cifDk,
  cifDj,
  cifDm,
  cifDo,
  cifCd,
  cifEc,
  cifEg,
  cifSv,
  cifGq,
  cifEr,
  cifEe,
  cifSz,
  cifEt,
  cifFj,
  cifFi,
  cifFr,
  cifGa,
  cifGm,
  cifGe,
  cifDe,
  cifGh,
  cifGr,
  cifGd,
  cifGt,
  cifGn,
  cifGw,
  cifGy,
  cifHt,
  cifHn,
  cifHk,
  cifHu,
  cifIs,
  cifIn,
  cifId,
  cifIr,
  cifIq,
  cifIe,
  cifIl,
  cifIt,
  cifCi,
  cifJm,
  cifJp,
  cifJo,
  cifKz,
  cifKe,
  cifKi,
  cifXk,
  cifKw,
  cifKg,
  cifLa,
  cifLv,
  cifLb,
  cifLs,
  cifLr,
  cifLy,
  cifLi,
  cifLt,
  cifLu,
  cifMg,
  cifMw,
  cifMy,
  cifMv,
  cifMl,
  cifMt,
  cifMh,
  cifMr,
  cifMu,
  cifMx,
  cifFm,
  cifMd,
  cifMc,
  cifMn,
  cifMe,
  cifMa,
  cifMz,
  cifMm,
  cifNa,
  cifNr,
  cifNp,
  cifNl,
  cifNz,
  cifNi,
  cifNe,
  cifNg,
  cifNu,
  cifKp,
  cifMk,
  cifNo,
  cifOm,
  cifPk,
  cifPw,
  cifPa,
  cifPg,
  cifPy,
  cifPe,
  cifPh,
  cifPl,
  cifPt,
  cifQa,
  cifCg,
  cifRo,
  cifRu,
  cifRw,
  cifKn,
  cifLc,
  cifVc,
  cifWs,
  cifSm,
  cifSa,
  cifSn,
  cifRs,
  cifSc,
  cifSl,
  cifSg,
  cifSk,
  cifSi,
  cifSb,
  cifSo,
  cifZa,
  cifKr,
  cifSs,
  cifEs,
  cifLk,
  cifSd,
  cifSr,
  cifSe,
  cifCh,
  cifSy,
  cifSt,
  cifTw,
  cifTj,
  cifTz,
  cifTh,
  cifTl,
  cifTg,
  cifTo,
  cifTt,
  cifTn,
  cifTr,
  cifTm,
  cifTv,
  cifUg,
  cifUa,
  cifAe,
  cifGb,
  cifUs,
  cifUy,
  cifUz,
  cifVa,
  cifVe,
  cifVn,
  cifYe,
  cifZm,
  cifZw,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow
} from '@coreui/icons';

export const iconSubset = {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifAf,
  cifAl,
  cifDz,
  cifAd,
  cifAo,
  cifAg,
  cifAr,
  cifAm,
  cifAu,
  cifAt,
  cifAz,
  cifBs,
  cifBh,
  cifBd,
  cifBb,
  cifBy,
  cifBe,
  cifBz,
  cifBj,
  cifBt,
  cifBo,
  cifBa,
  cifBw,
  cifBr,
  cifBn,
  cifBg,
  cifBf,
  cifBi,
  cifKh,
  cifCm,
  cifCa,
  cifCv,
  cifCf,
  cifTd,
  cifCl,
  cifCn,
  cifCo,
  cifKm,
  cifCr,
  cifHr,
  cifCu,
  cifCy,
  cifCz,
  cifDk,
  cifDj,
  cifDm,
  cifDo,
  cifCd,
  cifEc,
  cifEg,
  cifSv,
  cifGq,
  cifEr,
  cifEe,
  cifSz,
  cifEt,
  cifFj,
  cifFi,
  cifFr,
  cifGa,
  cifGm,
  cifGe,
  cifDe,
  cifGh,
  cifGr,
  cifGd,
  cifGt,
  cifGn,
  cifGw,
  cifGy,
  cifHt,
  cifHn,
  cifHk,
  cifHu,
  cifIs,
  cifIn,
  cifId,
  cifIr,
  cifIq,
  cifIe,
  cifIl,
  cifIt,
  cifCi,
  cifJm,
  cifJp,
  cifJo,
  cifKz,
  cifKe,
  cifKi,
  cifXk,
  cifKw,
  cifKg,
  cifLa,
  cifLv,
  cifLb,
  cifLs,
  cifLr,
  cifLy,
  cifLi,
  cifLt,
  cifLu,
  cifMg,
  cifMw,
  cifMy,
  cifMv,
  cifMl,
  cifMt,
  cifMh,
  cifMr,
  cifMu,
  cifMx,
  cifFm,
  cifMd,
  cifMc,
  cifMn,
  cifMe,
  cifMa,
  cifMz,
  cifMm,
  cifNa,
  cifNr,
  cifNp,
  cifNl,
  cifNz,
  cifNi,
  cifNe,
  cifNg,
  cifNu,
  cifKp,
  cifMk,
  cifNo,
  cifOm,
  cifPk,
  cifPw,
  cifPa,
  cifPg,
  cifPy,
  cifPe,
  cifPh,
  cifPl,
  cifPt,
  cifQa,
  cifCg,
  cifRo,
  cifRu,
  cifRw,
  cifKn,
  cifLc,
  cifVc,
  cifWs,
  cifSm,
  cifSa,
  cifSn,
  cifRs,
  cifSc,
  cifSl,
  cifSg,
  cifSk,
  cifSi,
  cifSb,
  cifSo,
  cifZa,
  cifKr,
  cifSs,
  cifEs,
  cifLk,
  cifSd,
  cifSr,
  cifSe,
  cifCh,
  cifSy,
  cifSt,
  cifTw,
  cifTj,
  cifTz,
  cifTh,
  cifTl,
  cifTg,
  cifTo,
  cifTt,
  cifTn,
  cifTr,
  cifTm,
  cifTv,
  cifUg,
  cifUa,
  cifAe,
  cifGb,
  cifUs,
  cifUy,
  cifUz,
  cifVa,
  cifVe,
  cifVn,
  cifYe,
  cifZm,
  cifZw,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow
};

export enum IconSubset {
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifAf = 'cifAf',
  cifAl = 'cifAl',
  cifDz = 'cifDz',
  cifAs = 'cifAs',
  cifAd = 'cifAd',
  cifAo = 'cifAo',
  cifAi = 'cifAi',
  cifAq = 'cifAq',
  cifAg = 'cifAg',
  cifAr = 'cifAr',
  cifAm = 'cifAm',
  cifAw = 'cifAw',
  cifAu = 'cifAu',
  cifAt = 'cifAt',
  cifAz = 'cifAz',
  cifBs = 'cifBs',
  cifBh = 'cifBh',
  cifBd = 'cifBd',
  cifBb = 'cifBb',
  cifBy = 'cifBy',
  cifBe = 'cifBe',
  cifBz = 'cifBz',
  cifBj = 'cifBj',
  cifBm = 'cifBm',
  cifBt = 'cifBt',
  cifBo = 'cifBo',
  cifBa = 'cifBa',
  cifBw = 'cifBw',
  cifBv = 'cifBv',
  cifBr = 'cifBr',
  cifIo = 'cifIo',
  cifVg = 'cifVg',
  cifBn = 'cifBn',
  cifBg = 'cifBg',
  cifBf = 'cifBf',
  cifBi = 'cifBi',
  cifKh = 'cifKh',
  cifCm = 'cifCm',
  cifCa = 'cifCa',
  cifCv = 'cifCv',
  cifBq = 'cifBq',
  cifKy = 'cifKy',
  cifCf = 'cifCf',
  cifTd = 'cifTd',
  cifCl = 'cifCl',
  cifCn = 'cifCn',
  cifCx = 'cifCx',
  cifCc = 'cifCc',
  cifCo = 'cifCo',
  cifKm = 'cifKm',
  cifCk = 'cifCk',
  cifCr = 'cifCr',
  cifHr = 'cifHr',
  cifCu = 'cifCu',
  cifCw = 'cifCw',
  cifCy = 'cifCy',
  cifCz = 'cifCz',
  cifDk = 'cifDk',
  cifDj = 'cifDj',
  cifDm = 'cifDm',
  cifDo = 'cifDo',
  cifCd = 'cifCd',
  cifEc = 'cifEc',
  cifEg = 'cifEg',
  cifSv = 'cifSv',
  cifGq = 'cifGq',
  cifEr = 'cifEr',
  cifEe = 'cifEe',
  cifSz = 'cifSz',
  cifEt = 'cifEt',
  cifFk = 'cifFk',
  cifFo = 'cifFo',
  cifFj = 'cifFj',
  cifFi = 'cifFi',
  cifFr = 'cifFr',
  cifGf = 'cifGf',
  cifPf = 'cifPf',
  cifTf = 'cifTf',
  cifGa = 'cifGa',
  cifGm = 'cifGm',
  cifGe = 'cifGe',
  cifDe = 'cifDe',
  cifGh = 'cifGh',
  cifGi = 'cifGi',
  cifGr = 'cifGr',
  cifGl = 'cifGl',
  cifGd = 'cifGd',
  cifGp = 'cifGp',
  cifGu = 'cifGu',
  cifGt = 'cifGt',
  cifGg = 'cifGg',
  cifGn = 'cifGn',
  cifGw = 'cifGw',
  cifGy = 'cifGy',
  cifHt = 'cifHt',
  cifHm = 'cifHm',
  cifHn = 'cifHn',
  cifHk = 'cifHk',
  cifHu = 'cifHu',
  cifIs = 'cifIs',
  cifIn = 'cifIn',
  cifId = 'cifId',
  cifIr = 'cifIr',
  cifIq = 'cifIq',
  cifIe = 'cifIe',
  cifIm = 'cifIm',
  cifIl = 'cifIl',
  cifIt = 'cifIt',
  cifCi = 'cifCi',
  cifJm = 'cifJm',
  cifJp = 'cifJp',
  cifJe = 'cifJe',
  cifJo = 'cifJo',
  cifKz = 'cifKz',
  cifKe = 'cifKe',
  cifKi = 'cifKi',
  cifXk = 'cifXk',
  cifKw = 'cifKw',
  cifKg = 'cifKg',
  cifLa = 'cifLa',
  cifLv = 'cifLv',
  cifLb = 'cifLb',
  cifLs = 'cifLs',
  cifLr = 'cifLr',
  cifLy = 'cifLy',
  cifLi = 'cifLi',
  cifLt = 'cifLt',
  cifLu = 'cifLu',
  cifMo = 'cifMo',
  cifMg = 'cifMg',
  cifMw = 'cifMw',
  cifMy = 'cifMy',
  cifMv = 'cifMv',
  cifMl = 'cifMl',
  cifMt = 'cifMt',
  cifMh = 'cifMh',
  cifMq = 'cifMq',
  cifMr = 'cifMr',
  cifMu = 'cifMu',
  cifYt = 'cifYt',
  cifMx = 'cifMx',
  cifFm = 'cifFm',
  cifMd = 'cifMd',
  cifMc = 'cifMc',
  cifMn = 'cifMn',
  cifMe = 'cifMe',
  cifMs = 'cifMs',
  cifMa = 'cifMa',
  cifMz = 'cifMz',
  cifMm = 'cifMm',
  cifNa = 'cifNa',
  cifNr = 'cifNr',
  cifNp = 'cifNp',
  cifNl = 'cifNl',
  cifNc = 'cifNc',
  cifNz = 'cifNz',
  cifNi = 'cifNi',
  cifNe = 'cifNe',
  cifNg = 'cifNg',
  cifNu = 'cifNu',
  cifNf = 'cifNf',
  cifKp = 'cifKp',
  cifMk = 'cifMk',
  cifMp = 'cifMp',
  cifNo = 'cifNo',
  cifOm = 'cifOm',
  cifPk = 'cifPk',
  cifPw = 'cifPw',
  cifPs = 'cifPs',
  cifPa = 'cifPa',
  cifPg = 'cifPg',
  cifPy = 'cifPy',
  cifPe = 'cifPe',
  cifPh = 'cifPh',
  cifPn = 'cifPn',
  cifPl = 'cifPl',
  cifPt = 'cifPt',
  cifPr = 'cifPr',
  cifQa = 'cifQa',
  cifCg = 'cifCg',
  cifRo = 'cifRo',
  cifRu = 'cifRu',
  cifRw = 'cifRw',
  cifRe = 'cifRe',
  cifBl = 'cifBl',
  cifSh = 'cifSh',
  cifKn = 'cifKn',
  cifLc = 'cifLc',
  cifMf = 'cifMf',
  cifPm = 'cifPm',
  cifVc = 'cifVc',
  cifWs = 'cifWs',
  cifSm = 'cifSm',
  cifSa = 'cifSa',
  cifSn = 'cifSn',
  cifRs = 'cifRs',
  cifSc = 'cifSc',
  cifSl = 'cifSl',
  cifSg = 'cifSg',
  cifSx = 'cifSx',
  cifSk = 'cifSk',
  cifSi = 'cifSi',
  cifSb = 'cifSb',
  cifSo = 'cifSo',
  cifZa = 'cifZa',
  cifGs = 'cifGs',
  cifKr = 'cifKr',
  cifSs = 'cifSs',
  cifEs = 'cifEs',
  cifLk = 'cifLk',
  cifSd = 'cifSd',
  cifSr = 'cifSr',
  cifSj = 'cifSj',
  cifSe = 'cifSe',
  cifCh = 'cifCh',
  cifSy = 'cifSy',
  cifSt = 'cifSt',
  cifTw = 'cifTw',
  cifTj = 'cifTj',
  cifTz = 'cifTz',
  cifTh = 'cifTh',
  cifTl = 'cifTl',
  cifTg = 'cifTg',
  cifTk = 'cifTk',
  cifTo = 'cifTo',
  cifTt = 'cifTt',
  cifTn = 'cifTn',
  cifTr = 'cifTr',
  cifTm = 'cifTm',
  cifTc = 'cifTc',
  cifTv = 'cifTv',
  cifUg = 'cifUg',
  cifUa = 'cifUa',
  cifAe = 'cifAe',
  cifGb = 'cifGb',
  cifUs = 'cifUs',
  cifUm = 'cifUm',
  cifVi = 'cifVi',
  cifUy = 'cifUy',
  cifUz = 'cifUz',
  cifVu = 'cifVu',
  cifVa = 'cifVa',
  cifVe = 'cifVe',
  cifVn = 'cifVn',
  cifWf = 'cifWf',
  cifEh = 'cifEh',
  cifYe = 'cifYe',
  cifZm = 'cifZm',
  cifZw = 'cifZw',
  cifAx = 'cifAx',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck = 'cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDescription = 'cilDescription',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFile = 'cilFile',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
}
